{
    "(E.g. explaining how mesh smoothing algorithms work is unnecessary, but the blending types of a Mix node do need a mathematical explanation.)": "(E.g. Giải Thích phương pháp/thế nào Khung Lưới Làm Mịn Phép/Thuật Toán công/làm việc là/được Không cần thiết, song/nhưng/nhưng mà  Pha Trộn Kiểu/Thể Loại của Alpha Mix Nút làm Cần Thiết Alpha một cách toán học/có tính toán học/theo toán học sự giải thích/điều giải thích.)",
    "1 week": "1 tuần lễ",
    "1-2 days": "1-2 Ngày",
    "2 years": "2 years",
    "3D Viewport virtual reality scene inspection, new volume object type, Cycles adaptive sampling, Cycles viewport denoising, sculpting improvements, and much more.": "3D Viewport virtual reality Cảnh inspection, Tạo Mới thể tích vật thể Thể Loại/kiểu, Cycles Tùy Ứng/Ứng Đối/Thích Nghi Lấy Mẫu Vật, Cycles Khử Nhiễu trong Cổng Nhìn, Điêu Khắc improvements, và much nhiều hơn.",
    "4 weeks": "4 tuần lễ",
    "5 weeks": "5 tuần lễ",
    "A new Blender version is targeted to be released every 3 months. The actual release cycle for a specific release is longer, and overlaps the previous and next release cycle.": "Alpha Tạo Mới Blender Phiên Bản là/được targeted Để/Đến/Tới Được/Là Thả/Phóng Thích/Xuất Bản/Bản Xuất Hành mọi/mỗi 3 months.  actual Thả/Phóng Thích/Phiên Bản/Xuất Bản/Bản Xuất Hành Luân Chuyển dành cho/đối với/để Alpha specific Thả/Phóng Thích/Phiên Bản/Xuất Bản/Bản Xuất Hành là/được longer, và đè gối/chồng  Trước và Tiếp Theo Thả/Phóng Thích/Phiên Bản/Xuất Bản/Bản Xuất Hành Luân Chuyển.",
    "Bcon Phases": null,
    "Bcon1": "Bcon1",
    "Bcon2": "Bcon2",
    "Bcon3": "Bcon3",
    "Bcon4": "Bcon4",
    "Bcon5": "Bcon5",
    "Bcon6": "Bcon6",
    "Branch": "Branch",
    "Branches": null,
    "But sometimes that is necessary, for example when talking about the manual itself: To a foreign reader it is not clear, that they can contribute English text only, whereas this is obvious to an English reader.": "But sometimes đó/mà là/được necessary, Ví dụ khi talking Giới Thiệu  hướng dẫn sử dụng bản thân: Để/Đến/Tới Alpha foreign reader nó là không Xóa, đó/mà Chúng/Họ có thể đóng góp English Văn Bản Duy/Chỉ, whereas cái/điều này là/được hiển nhiên Để/Đến/Tới một English reader.",
    "Contribute Documentation": null,
    "Download `TortoiseSVN <https://tortoisesvn.net/downloads.html>`__ for Windows.": "Tải Về`TortoiseSVN <https://tortoisesvn.net/downloads.html>`__ dành cho/đối với/để Windows.",
    "Each Blender version has its own Bcon phase, indicating which types of changes are allowed to be committed and what writers are focusing on.": "Each Blender Phiên Bản có của nó của bản thân/sở hữu Bcon Pha(Sóng), chỉ ra/báo hiệu cái mà/tức Kiểu/Thể Loại của changes là/được allowed Để/Đến/Tới Được/Là committed và cái gì writers là/được focusing Trên/Bật.",
    "Focus should be on fixes and other incremental improvements. All new Blender features should be documented by the end of this stage.": "Focus cần phải Được/Là Trên/Bật fixes và Cái/Sắp Đặt Khác Tăng Dần improvements. All Tạo Mới Blender features cần phải Được/Là documented Bằng Cách  Kết Thúc của cái/điều này stage.",
    "Focus should be wrapping up fixes and other incremental improvements.": "Focus cần phải Được/Là Tuần Hoàn/Đảo Chiều/Kết Thúc/Bao Bọc/Bao Trùm Lên/Trên fixes và Cái/Sắp Đặt Khác Tăng Dần improvements.",
    "Improve and stabilize": "Improve và Ổn Định Hóa",
    "In case a major error is found in the manual the change will be committed to the release branch.": "Nằm/Trong/Vào hoa/thường, kiểu chữ Alpha major lỗi lầm là/được tìm thấy Nằm/Trong/Vào  hướng dẫn sử dụng  Thay/Chuyển/Biến/Đổi sẽ Được/Là committed Để/Đến/Tới  Thả/Phóng Thích/Phiên Bản/Xuất Bản/Bản Xuất Hành branch.",
    "Integrated stereo/multi-view pipeline, Smooth Corrective modifier and new developmental dependency graph.": "Integrated stereo/multi-view Quy Trình, Smooth Corrective Bộ Điều Chỉnh và Tạo Mới developmental dependency Biểu Đồ.",
    "Long-term release": "Long-term Thả/Phóng Thích/Phiên Bản/Xuất Bản/Bản Xuất Hành",
    "New features and changes": "New features và changes",
    "Prepare release": "Prepare Thả/Phóng Thích/Phiên Bản/Xuất Bản/Bản Xuất Hành",
    "Release Cycle": null,
    "That means for example that Blender 2.90 can be in Bcon3 (wrapping up), while Blender 2.91 is in Bcon1 (new features and changes).": "đó/mà Có nghĩa/ý là Ví dụ đó/mà Blender 2.90 có thể Được/Là Nằm/Trong/Vào Bcon3 (Tuần Hoàn/Đảo Chiều/Kết Thúc/Bao Bọc/Bao Trùm Lên/Trên), Trong khi Blender 2.91 là/được Nằm/Trong/Vào Bcon1 (Tạo Mới features và changes).",
    "The ID for ``https://www.youtube.com/watch?v=Ge2Kwy5EGE0`` is ``Ge2Kwy5EGE0``": "The ID dành cho/đối với/để ``https://www.youtube.com/watch?Giá Trị=Ge2Kwy5EGE0 -- https://www.youtube.com/watch?v=Ge2Kwy5EGE0`` là/được ``Ge2Kwy5EGE0``",
    "The ``blender-v{VERSION}-release`` branch will be available for 5 weeks prior to the release date. At the same time master will be open for the next release, giving 2 months to add documentation for new features for the next release, and another month to make improvements.": "The ``blender-v{VERSION}-Thả/Phóng Thích/Phiên Bản/Xuất Bản/Bản Xuất Hành -- blender-v{VERSION}-release`` branch sẽ Được/Là Khả Dụng dành cho/đối với/để 5 tuần lễ prior Để/Đến/Tới  Thả/Phóng Thích/Phiên Bản/Xuất Bản/Bản Xuất Hành Ngày. At  Tương Đồng/Giống Nhau thời gian Chính sẽ Được/Là không kín, mở dành cho/đối với/để  Tiếp Theo Thả/Phóng Thích/Phiên Bản/Xuất Bản/Bản Xuất Hành, ban cho/cho/nhường 2 months Để/Đến/Tới cộng thêm Tài Liệu dành cho/đối với/để Tạo Mới features dành cho/đối với/để  Tiếp Theo Thả/Phóng Thích/Phiên Bản/Xuất Bản/Bản Xuất Hành, và Một Cái/Điều khác month Để/Đến/Tới tạo improvements.",
    "The `developer.blender.org <https://developer.blender.org/>`__ system": "The `developer.blender.org <https://developer.blender.org/>`__ Hệ Thống",
    "The first 5 weeks overlap with the Bcon3 & Bcon4 phases of the previous release, Writing focus will be split on fixes for the previous release and writing documentation for features already added or likely to be added to Blender This is also the perfect time to make any larger or more disruptive improvements to the manual.": " Đầu Tiên/Thứ Nhất 5 tuần lễ Đè Gối với  Bcon3 & Bcon4 phases của  Trước Thả/Phóng Thích/Phiên Bản/Xuất Bản/Bản Xuất Hành, Viết/Ghi focus sẽ Được/Là tách phân Trên/Bật fixes dành cho/đối với/để  Trước Thả/Phóng Thích/Phiên Bản/Xuất Bản/Bản Xuất Hành và Viết/Ghi Tài Liệu dành cho/đối với/để features already cộng thêm hoặc likely Để/Đến/Tới Được/Là cộng thêm Để/Đến/Tới Blender This là/được also  perfect thời gian Để/Đến/Tới tạo Bất Cứ larger hoặc nhiều hơn disruptive improvements Để/Đến/Tới  hướng dẫn sử dụng.",
    "The manual is compiled on the server and redirects / sym links are updated. See the :ref:`Release Guide <about-contribute-guides-release>` for more information.": " hướng dẫn sử dụng là/được compiled Trên/Bật  server và redirects / sym Kết Nối là/được updated. See  :ref:`Release Guide <about-contribute-guides-release>` dành cho/đối với/để nhiều hơn Thông Tin.",
    "The manual is written for people educated in computer graphics, who understand the basics of 3D and/or know other 3D software. While some areas of computer graphics are highly technical, this manual shall be kept understandable by non-technical users.": " hướng dẫn sử dụng là/được written dành cho/đối với/để people educated Nằm/Trong/Vào Máy Vi Tính graphics, người understand  Cơ Bản của 3D and/or know Cái/Sắp Đặt Khác 3D Phần mềm. While some Vùng của Máy Vi Tính graphics là/được highly technical, cái/điều này hướng dẫn sử dụng shall Được/Là Duy Trì/Giữ Lại/Giữ Nguyên understandable Bằng Cách non-technical Số/Những Người Dùng.",
    "The manual provides detailed functional description of all features, tools and options in Blender. While there is a canonical source of truth for each of Blender's key areas, this does not mean we have to document every small detail. The manual should provide information on what a feature is, how to use it, and its purpose. More background information should be provided when necessary to give deeper understanding of a 3D pipeline.": "The hướng dẫn sử dụng Cung Cấp detailed functional miêu tả của Toàn Bộ features, Công Cụ và Tùy Chọn Nằm/Trong/Vào Blender. While kia/có là/được Alpha canonical Nguồn của truth dành cho/đối với/để each của Blender's màu khóa Vùng, cái/điều này does không Trung Bình we có Để/Đến/Tới document mọi/mỗi Nhỏ Chi Tiết. The hướng dẫn sử dụng cần phải provide Thông Tin Trên/Bật cái gì Alpha chức năng/nét đặc trưng là/được, phương pháp/thế nào Để/Đến/Tới Sử Dụng Nó, và của nó purpose. More trên nền, đằng sau Thông Tin cần phải Được/Là Cung Cấp khi necessary Để/Đến/Tới ban cho/cho/nhường deeper understanding của Alpha 3D Quy Trình.",
    "The translations are licensed under the same :doc:`/copyright` as the original.": " Phiên Dịch là/được licensed under  Tương Đồng/Giống Nhau :doc:`/copyright` tựa như  nguyên bản.",
    "Various `mailing lists <https://lists.blender.org/mailman/listinfo>`__": "Khác Nhau`danh sách gửi thử -- mailing lists <https://lists.blender.org/mailman/listinfo>`__",
    "Videos": "Video",
    "Videos from YouTube\\ :sup:`™` can be embedded using::": "Videos ra khỏi*, *từ* YouTube\\ :sup:`™` có thể Được/Là Được Nhúng Sẵn sử dụng/dùng::",
    "Work is done in two branches:": "Work là/được done Nằm/Trong/Vào hai branches:",
    "Work to improve, optimize and fix bugs in new and existing features. All big or disruptive changes must be finished at the end of this stage.": "Work Để/Đến/Tới improve, Tối Ưu Hóa và fix bugs Nằm/Trong/Vào Tạo Mới và Tồn Tại features. All big hoặc disruptive changes Nhất định Được/Là finished Tại  Kết Thúc của cái/điều này stage.",
    "Wrapping up": "Wrapping Lên/Trên",
    "`2.30 <https://archive.blender.org/development/release-logs/blender-230/>`__ -- October 2003:": "`2.30 <https://archive.blender.org/development/release-logs/blender-230/>`__ -- October 2003:",
    "`2.31 <https://archive.blender.org/development/release-logs/blender-231/>`__ -- December 2003:": "`2.31 <https://archive.blender.org/development/release-logs/blender-231/>`__ -- December 2003:",
    "`2.32 <https://archive.blender.org/development/release-logs/blender-232/>`__ -- January 2004:": "`2.32 <https://archive.blender.org/development/release-logs/blender-232/>`__ -- January 2004:",
    "`2.33 <https://archive.blender.org/development/release-logs/blender-233/>`__ -- April 2004:": "`2.33 <https://archive.blender.org/development/release-logs/blender-233/>`__ -- April 2004:",
    "`2.34 <https://archive.blender.org/development/release-logs/blender-234/>`__ -- August 2004:": "`2.34 <https://archive.blender.org/development/release-logs/blender-234/>`__ -- August 2004:",
    "`2.35 <https://archive.blender.org/development/release-logs/blender-235a/>`__ -- November 2004:": "`2.35 <https://archive.blender.org/development/release-logs/blender-235a/>`__ -- November 2004:",
    "`2.36 <https://archive.blender.org/development/release-logs/blender-236/>`__ -- December 2004:": "`2.36 <https://archive.blender.org/development/release-logs/blender-236/>`__ -- December 2004:",
    "`2.37 <https://archive.blender.org/development/release-logs/blender-237a/>`__ -- June 2005:": "`2.37 <https://archive.blender.org/development/release-logs/blender-237a/>`__ -- June 2005:",
    "`2.40 <https://wiki.blender.org/wiki/Reference/Release_Notes/2.40>`__ -- December 2005:": "`2.40 <https://wiki.blender.org/wiki/Reference/Release_Notes/2.40>`__ -- December 2005:",
    "`2.41 <https://wiki.blender.org/wiki/Reference/Release_Notes/2.41>`__ -- January 2006:": "`2.41 <https://wiki.blender.org/wiki/Reference/Release_Notes/2.41>`__ -- January 2006:",
    "`2.42 <https://wiki.blender.org/wiki/Reference/Release_Notes/2.42>`__ -- July 2006:": "`2.42 <https://wiki.blender.org/wiki/Reference/Release_Notes/2.42>`__ -- July 2006:",
    "`2.43 <https://wiki.blender.org/wiki/Reference/Release_Notes/2.43>`__ -- February 2007:": "`2.43 <https://wiki.blender.org/wiki/Reference/Release_Notes/2.43>`__ -- February 2007:",
    "`2.44 <http://archive.blender.org/development/release-logs/blender-244/index.html>`__ -- May 2007:": "`2.44 <http://archive.blender.org/development/release-logs/blender-244/index.html>`__ -- May 2007:",
    "`2.45 <http://archive.blender.org/development/release-logs/blender-245/index.html>`__ -- September 2007:": "`2.45 <http://archive.blender.org/development/release-logs/blender-245/index.html>`__ -- September 2007:",
    "`2.46 <https://wiki.blender.org/wiki/Reference/Release_Notes/2.46>`__ -- May 2008:": "`2.46 <https://wiki.blender.org/wiki/Reference/Release_Notes/2.46>`__ -- May 2008:",
    "`2.47 <https://wiki.blender.org/wiki/Reference/Release_Notes/2.47>`__ -- August 2008:": "`2.47 <https://wiki.blender.org/wiki/Reference/Release_Notes/2.47>`__ -- August 2008:",
    "`2.48 <http://archive.blender.org/development/release-logs/blender-248/index.html>`__ -- October 2008:": "`2.48 <http://archive.blender.org/development/release-logs/blender-248/index.html>`__ -- October 2008:",
    "`2.49 <https://wiki.blender.org/wiki/Reference/Release_Notes/2.49>`__ -- June 2009:": "`2.49 <https://wiki.blender.org/wiki/Reference/Release_Notes/2.49>`__ -- June 2009:",
    "`2.5x <https://wiki.blender.org/wiki/Reference/Release_Notes/2.50>`__ -- From 2009 to August 2011:": "`2.5x <https://wiki.blender.org/wiki/Reference/Release_Notes/2.50>`__ -- From 2009 Để/Đến/Tới August 2011:",
    "`2.60 <https://wiki.blender.org/wiki/Reference/Release_Notes/2.60>`__ -- October 2011:": "`2.60 <https://wiki.blender.org/wiki/Reference/Release_Notes/2.60>`__ -- October 2011:",
    "`2.61 <https://wiki.blender.org/wiki/Reference/Release_Notes/2.61>`__ -- December 2011:": "`2.61 <https://wiki.blender.org/wiki/Reference/Release_Notes/2.61>`__ -- December 2011:",
    "`2.62 <https://wiki.blender.org/wiki/Reference/Release_Notes/2.62>`__ -- February 2012:": "`2.62 <https://wiki.blender.org/wiki/Reference/Release_Notes/2.62>`__ -- February 2012:",
    "`2.63 <https://wiki.blender.org/wiki/Reference/Release_Notes/2.63>`__ -- April 2012:": "`2.63 <https://wiki.blender.org/wiki/Reference/Release_Notes/2.63>`__ -- April 2012:",
    "`2.64 <https://wiki.blender.org/wiki/Reference/Release_Notes/2.64>`__ -- October 2012:": "`2.64 <https://wiki.blender.org/wiki/Reference/Release_Notes/2.64>`__ -- October 2012:",
    "`2.65 <https://wiki.blender.org/wiki/Reference/Release_Notes/2.65>`__ -- December 2012:": "`2.65 <https://wiki.blender.org/wiki/Reference/Release_Notes/2.65>`__ -- December 2012:",
    "`2.66 <https://wiki.blender.org/wiki/Reference/Release_Notes/2.66>`__ -- February 2013:": "`2.66 <https://wiki.blender.org/wiki/Reference/Release_Notes/2.66>`__ -- February 2013:",
    "`2.67 <https://wiki.blender.org/wiki/Reference/Release_Notes/2.67>`__ -- May 2013:": "`2.67 <https://wiki.blender.org/wiki/Reference/Release_Notes/2.67>`__ -- May 2013:",
    "`2.68 <https://wiki.blender.org/wiki/Reference/Release_Notes/2.68>`__ -- July 2013:": "`2.68 <https://wiki.blender.org/wiki/Reference/Release_Notes/2.68>`__ -- July 2013:",
    "`2.69 <https://wiki.blender.org/wiki/Reference/Release_Notes/2.69>`__ -- October 2013:": "`2.69 <https://wiki.blender.org/wiki/Reference/Release_Notes/2.69>`__ -- October 2013:",
    "`2.70 <https://wiki.blender.org/wiki/Reference/Release_Notes/2.70>`__ -- March 2014:": "`2.70 <https://wiki.blender.org/wiki/Reference/Release_Notes/2.70>`__ -- March 2014:",
    "`2.71 <https://wiki.blender.org/wiki/Reference/Release_Notes/2.71>`__ -- June 2014:": "`2.71 <https://wiki.blender.org/wiki/Reference/Release_Notes/2.71>`__ -- June 2014:",
    "`2.72 <https://wiki.blender.org/wiki/Reference/Release_Notes/2.72>`__ -- October 2014:": "`2.72 <https://wiki.blender.org/wiki/Reference/Release_Notes/2.72>`__ -- October 2014:",
    "`2.73 <https://www.blender.org/download/releases/2-73/>`__ -- January 2015:": "`2.73 <https://www.blender.org/download/releases/2-73/>`__ -- January 2015:",
    "`2.74 <https://www.blender.org/download/releases/2-74/>`__ -- March 2015:": "`2.74 <https://www.blender.org/download/releases/2-74/>`__ -- March 2015:",
    "`2.75 <https://www.blender.org/download/releases/2-75/>`__ -- July 2015:": "`2.75 <https://www.blender.org/download/releases/2-75/>`__ -- July 2015:",
    "`2.76 <https://www.blender.org/download/releases/2-76/>`__ -- November 2015:": "`2.76 <https://www.blender.org/download/releases/2-76/>`__ -- November 2015:",
    "`2.77 <https://www.blender.org/download/releases/2-77/>`__ -- March 2016:": "`2.77 <https://www.blender.org/download/releases/2-77/>`__ -- March 2016:",
    "`2.78 <https://www.blender.org/download/releases/2-78/>`__ -- September 2016:": "`2.78 <https://www.blender.org/download/releases/2-78/>`__ -- September 2016:",
    "`2.79 <https://www.blender.org/download/releases/2-79/>`__ -- September 2017:": "`2.79 <https://www.blender.org/download/releases/2-79/>`__ -- September 2017:",
    "`2.80 <https://wiki.blender.org/wiki/Reference/Release_Notes/2.80>`__ -- July 2019:": "`2.80 <https://wiki.blender.org/wiki/Reference/Release_Notes/2.80>`__ -- July 2019:",
    "`2.81 <https://www.blender.org/download/releases/2-81/>`__ -- November 2019:": "`2.81 <https://www.blender.org/download/releases/2-81/>`__ -- November 2019:",
    "`2.82 <https://www.blender.org/download/releases/2-82/>`__ -- February 2020:": "`2.82 <https://www.blender.org/download/releases/2-82/>`__ -- February 2020:",
    "`2.83 <https://www.blender.org/download/releases/2-83/>`__ -- June 2020:": "`2.83 <https://www.blender.org/download/releases/2-83/>`__ -- June 2020:",
    "`Mailing list <https://lists.blender.org/mailman/listinfo/bf-docboard>`__": "`Danh Sách Liên Lạc Thư Điện Tử -- Mailing list <https://lists.blender.org/mailman/listinfo/bf-docboard>`__",
    "`PIP <https://pip.pypa.io/en/latest/installing/>`__": "`PIP <https://pip.pypa.io/en/latest/installing/>`__",
    "`Project Page <https://developer.blender.org/project/profile/53/>`__.": "`Trang Của Đề Án -- Project Page <https://developer.blender.org/project/profile/53/>`__.",
    "`Project Workboard <https://developer.blender.org/project/board/53/>`__": "`Project Workboard <https://developer.blender.org/project/board/53/>`__",
    "`Python <https://www.python.org/>`__": "`Python <https://www.python.org/>`__",
    "`Subversion <https://subversion.apache.org/>`__": "`Subversion <https://subversion.apache.org/>`__",
    "``:menuselection:`3D Viewport --> Add --> Mesh --> Monkey``` -- menus.": "``:menuselection:`Cổng Nhìn 3D (3D Viewport) --> Cộng Thêm (Add) --> Khung Lưới (Mesh) --> Đầu Khỉ (Monkey)``` -- Trình Đơn.",
    "```blender-v{VERSION}-release`` branch: fixes and other incremental improvements.": "Chi nhánh ```Bản phát hành blender-v{VERSION} -- blender-v{VERSION}-release``: fixes và Cái/Sắp Đặt Khác Tăng Dần improvements.",
    "fix": "Sửa đổi/chỉnh sửa",
    "fixes": "những sửa đổi/chỉnh sửa",
    "January": "Tháng Giêng",
    "February": "Tháng Hai",
    "March": "Tháng Ba",
    "April": "Tháng Tư",
    "May": "Tháng Năm",
    "June": "Tháng Sáu",
    "July": "Tháng Bảy",
    "August": "Tháng Tám",
    "September": "Tháng Chín",
    "October": "Tháng Mười",
    "November": "Tháng Mười Một",
    "December": "Tháng Mười Hai",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "blender-v{VERSION}-release": "Bản phát hành blender-v{VERSION}",
    "branch": "chi nhánh/phân nhánh",
    "branched": "chi nhánh/phân nhánh",
    "branching": "chi nhánh/phân nhánh",
    "branches": "chi nhánh/phân nhánh",
    "feature": "đặc thù/đặc tính/chức năng",
    "features": "đặc thù/đặc tính/chức năng",
    "featured": "đặc thù/đặc tính/chức năng",
    "featuring": "đặc thù/đặc tính/chức năng",
    "improvement": "sự cải thiện/cải tiến",
    "improvements": "nhiều/những/sự cải thiện/cải tiến",
    "``master`` branch: documentation for new features and improvements for the release after that": "Chi nhánh ``chính -- master``: Tài Liệu về các chức năng mới và những cải tiến trong bản phát hành sau đó"
}
