/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.htran.translationpomaven;

import java.awt.Font;
import java.util.Enumeration;
import javax.swing.JFrame;
import javax.swing.UIManager;
import javax.swing.plaf.FontUIResource;

/**
 *
 * @author Hoang Duy Tran <hoangduytran1960@gmail.com>
 */
public class StartScreen extends javax.swing.JFrame {

    /**
     * Creates new form StartScreen
     */
    public StartScreen() {
        //UIManager.put("Label.font", UIManager.getFont("Label.font").deriveFont(24));
        //SwingUtilities.updateComponentTreeUI(this);

        setUIFont(new FontUIResource(new Font("Arial", 0, 18)));
        
        initComponents();
    }

    public void setUIFont(FontUIResource f) {
        Enumeration keys = UIManager.getDefaults().keys();
        while (keys.hasMoreElements()) {
            Object key = keys.nextElement();
            Object value = UIManager.get(key);
            if (value instanceof FontUIResource) {
                FontUIResource orig = (FontUIResource) value;
                Font font = new Font(f.getFontName(), orig.getStyle(), f.getSize());
                UIManager.put(key, new FontUIResource(font));
            }
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TextTable = new javax.swing.JTable();
        BottomButtonPanel = new javax.swing.JPanel();
        SaveFileLeft = new javax.swing.JButton();
        ButtonPreviousFile = new javax.swing.JButton();
        ButtonNextFile = new javax.swing.JButton();
        SaveFileRight = new javax.swing.JButton();
        MainMenuBar = new javax.swing.JMenuBar();
        MenuFile = new javax.swing.JMenu();
        FileNewComparison = new javax.swing.JMenuItem();
        FileExit = new javax.swing.JMenuItem();
        MenuEdit = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                StartScreenWindowsActivated(evt);
            }
        });

        TextTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(TextTable);

        SaveFileLeft.setText("Save File");

        ButtonPreviousFile.setText("Previous File");

        ButtonNextFile.setText("Next File");

        SaveFileRight.setText("Save File");

        javax.swing.GroupLayout BottomButtonPanelLayout = new javax.swing.GroupLayout(BottomButtonPanel);
        BottomButtonPanel.setLayout(BottomButtonPanelLayout);
        BottomButtonPanelLayout.setHorizontalGroup(
            BottomButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BottomButtonPanelLayout.createSequentialGroup()
                .addComponent(SaveFileLeft)
                .addGap(135, 135, 135)
                .addComponent(ButtonPreviousFile)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 239, Short.MAX_VALUE)
                .addComponent(ButtonNextFile)
                .addGap(48, 48, 48)
                .addComponent(SaveFileRight)
                .addContainerGap())
        );
        BottomButtonPanelLayout.setVerticalGroup(
            BottomButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BottomButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(SaveFileLeft)
                .addComponent(ButtonPreviousFile)
                .addComponent(ButtonNextFile)
                .addComponent(SaveFileRight))
        );

        MenuFile.setText("File");

        FileNewComparison.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_K, java.awt.event.InputEvent.ALT_MASK));
        FileNewComparison.setText("New Comparison");
        FileNewComparison.setActionCommand("New Comparison");
        FileNewComparison.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FileNewComparisonActionPerformed(evt);
            }
        });
        MenuFile.add(FileNewComparison);

        FileExit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_MASK));
        FileExit.setText("Exit");
        FileExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FileExitActionPerformed(evt);
            }
        });
        MenuFile.add(FileExit);

        MainMenuBar.add(MenuFile);

        MenuEdit.setText("Edit");
        MainMenuBar.add(MenuEdit);

        setJMenuBar(MainMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addComponent(BottomButtonPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BottomButtonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(87, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void StartScreenWindowsActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_StartScreenWindowsActivated
        // TODO add your handling code here:
        this.setExtendedState(this.getExtendedState() | JFrame.MAXIMIZED_BOTH);
    }//GEN-LAST:event_StartScreenWindowsActivated

    private void FileNewComparisonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FileNewComparisonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FileNewComparisonActionPerformed

    private void FileExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FileExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_FileExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StartScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StartScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StartScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StartScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StartScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BottomButtonPanel;
    private javax.swing.JButton ButtonNextFile;
    private javax.swing.JButton ButtonPreviousFile;
    private javax.swing.JMenuItem FileExit;
    private javax.swing.JMenuItem FileNewComparison;
    private javax.swing.JMenuBar MainMenuBar;
    private javax.swing.JMenu MenuEdit;
    private javax.swing.JMenu MenuFile;
    private javax.swing.JButton SaveFileLeft;
    private javax.swing.JButton SaveFileRight;
    private javax.swing.JTable TextTable;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
